### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by shadowdragon007** [kumarasinghe/linkedin-learning-downloader#3]
C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master>npm start

> linkedin-downloader@1.0.0 start C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master
> node index.js

Detected 2 courses.
Download directory:C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\downloads
Parsing course 2 of 2:
(node:21152) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\Connection.js:156:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\Connection.js:155:16)
    at navigate (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\FrameManager.js:88:47)
    at FrameManager.navigateFrame (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\FrameManager.js:71:13)
    at Frame.goto (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\FrameManager.js:295:41)
    at Frame.<anonymous> (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\helper.js:117:27)
    at Page.goto (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\Page.js:553:53)
    at Page.<anonymous> (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\helper.js:117:27)
    at downloadCourses (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\index.js:91:20)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\helper.js:116:19)
    at Page.goto (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\Page.js:553:53)
    at Page.<anonymous> (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\helper.js:117:27)
    at downloadCourses (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\index.js:91:20)
    at C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\index.js:65:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:21152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master>npm start

> linkedin-downloader@1.0.0 start C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master
> node index.js

Detected 2 courses.
Download directory:C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\downloads
Parsing course 2 of 2:
(node:1012) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\Connection.js:156:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\Connection.js:155:16)
    at navigate (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\FrameManager.js:88:47)
    at FrameManager.navigateFrame (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\FrameManager.js:71:13)
    at Frame.goto (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\FrameManager.js:295:41)
    at Frame.<anonymous> (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\helper.js:117:27)
    at Page.goto (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\Page.js:553:53)
    at Page.<anonymous> (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\helper.js:117:27)
    at downloadCourses (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\index.js:91:20)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\helper.js:116:19)
    at Page.goto (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\Page.js:553:53)
    at Page.<anonymous> (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\node_modules\puppeteer-core\lib\helper.js:117:27)
    at downloadCourses (C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\index.js:91:20)
    at C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\index.js:65:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kumarasinghe** [comment]
Please post your course link file

**Comment by shadowdragon007** [comment]
#https://www.linkedin.com/learning/advocating-for-change-in-your-organization/real-change-is-possible?u=22952571

**Comment by kumarasinghe** [comment]
Please re-format it to:
https://www.linkedin.com/learning/advocating-for-change-in-your-organization

**Comment by shadowdragon007** [comment]
C:\Users\Dragoon\Downloads\Compressed\linkedin-learning-downloader-master>npm start

> linkedin-downloader@1.0.0 start C:\Users\Dragoon\Downloads\Compressed\linkedin-learning-downloader-master
> node index.js

Detected 1 courses.
Download directory:C:\Users\Dragoon\Downloads\Compressed\linkedin-learning-downloader-master\downloads
Program ended.
